version: "3"

services:
  mysql:
    container_name: study-mysql
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWRD: mysql
